### ISSUE TITLE
Support for OS to send led status

### ISSUE THREAD

**Issue by StarlightNL** [arpruss/USBHID_stm32f1#3]
I am trying to revive a old keyboard and your library works like a charm but I am missing the ability to get the led status report. Is it implemented and if so how can I get that?

P.S. What is the status on Consumer. Every time I try to send a keypress the stm32(Blue pill) freezes

**Comment by arpruss** [comment]
1. Does the LED status report go from the keyboard to the PC or the PC to the keyboard?

2. Did you try the consumer example? It worked for me.

**Comment by arpruss** [comment]
Somehow the Consumer.cpp file never got committed to the repository. Fixed.

**Comment by StarlightNL** [comment]
From [https://docs.mbed.com/docs/ble-hid/en/latest/api/md_doc_HID.html](https://docs.mbed.com/docs/ble-hid/en/latest/api/md_doc_HID.html) it says that the os is sending an output record to the device. After seeing that I guess that the report descriptors for the keyboard needs to be changed.

**Comment by arpruss** [comment]
Added keyboardwithleds example (and updated the library code to allow LEDs to work without constant polling).
